config/routes.rb
Rails.application.routes.draw do
  root 'best_nines#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :best_nines,  only: [:new, :create, :show, :destroy] do
    collection do
      post 'confirm'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/best_nine.rb
class BestNine < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  default_scope -> {order(created_at: :desc)}

  validates :title, presence: true, length:{maximum: 30}
  validates :one_position, presence: true
  validates :one_name, presence: true
  validates :two_position, presence: true
  validates :two_name, presence: true
  validates :three_position, presence: true
  validates :three_name, presence: true
  validates :four_position, presence: true
  validates :four_name, presence: true
  validates :five_position, presence: true
  validates :five_name, presence: true
  validates :six_position, presence: true
  validates :six_name, presence: true
  validates :seven_position, presence: true
  validates :seven_name, presence: true
  validates :eight_position, presence: true
  validates :eight_name, presence: true
  validates :nine_position, presence: true
  validates :nine_name, presence: true
  validates :starting, presence: true
  validates :relief, presence: true
  validates :closer, presence: true

  POSITION = {'捕': 2, '一': 3, '二': 4, '三': 5, '遊': 6, '左': 7, '中': 8, '右': 9, 'DH': 10}

end

app/models/player.rb
class Player < ApplicationRecord  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :best_nines, dependent: :destroy

  before_save {email.downcase!}
  validates :name, presence: true, length: {maximum: 30}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX}, uniqueness: true
  validates :password, presence: true, length: {minimum: 8, maximum: 32}, allow_nil: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/best_nines_controller.rb
class BestNinesController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :create, :destroy]

  def index
    @best_nines = BestNine.paginate(page: params[:page], per_page: 2)
    @players = Player.all
  end

  def show
    @best_nine = BestNine.find(params[:id])
    @players = Player.all
  end

  def new
    @bestnine = BestNine.new
    @players_fielder = Player.where(field: "F").where(team: "C")
    @players_pitcher = Player.where(field: "P").where(team: "C")
  end

  def confirm
    @bestnine = BestNine.new(best_nine_params)
    render :new if @bestnine.invalid?
  end


  def create
    @bestnine = BestNine.new(best_nine_params)
    @players_fielder = Player.where(field: "F").where(team: "C")
    @players_pitcher = Player.where(field: "P").where(team: "C")

    # ポジション/選手に重複があるかの確認
    
    field_player = params[:best_nine].values[1..-5]
    pitcher = params[:best_nine].values[-4..-2]

    position = field_player.each_slice(2).map(&:first) # {|n| n.first}
    player = field_player.each_slice(2).map(&:last).push(pitcher)
    player.flatten!

    if ((position.count - position.uniq.count) != 0 || (player.count - player.uniq.count) != 0)
      flash[:danger] = "ポジションまたは選手が重複しています。"
      render :new
    elsif @bestnine.save
      flash[:success] = "ベストナインを作成しました。"
      redirect_to root_url
    else
      flash[:danger] = "保存に失敗しました。"
      render :new
    end
  end

  def destroy
    BestNine.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to root_url
  end



  private
    def best_nine_params
      params.require(:best_nine).permit(:title, :one_position, :one_name, :two_position, :two_name, :three_position, :three_name, :four_position, :four_name,
                                        :five_position, :five_name, :six_position, :six_name, :seven_position, :seven_name, :eight_position, :eight_name,
                                        :nine_position, :nine_name, :starting, :relief, :closer, :user_id)
    end

    def require_user_logged_in
      unless logged_in?
        redirect_to root_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_back_or(user)
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "登録が完了しました。"
      redirect_to @user
    else
      flash[:danger] = "登録に失敗しました。"
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を変更しました。"
      redirect_to @user
    else
      render "edit"
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインして下さい"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/best_nines_helper.rb
module BestNinesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user?(user)
    user && user == current_user
  end

  # 記憶したURL/デフォルト値にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURL
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/best_nines/confirm.html.erb
<h1>確認ページ</h1>

<div class="row">
  <%= form_with(model: @bestnine, local: true) do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
    <table border="1">
      <caption><%= f.text_field :title, placeholder: "タイトル" %></caption>
      <tr>
        <th>打順</th><th>ポジション</th><th>名前</th>
      </tr>
      <tr>
        <td>1</td>
        <td><%= f.select :one_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :one_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>2</td>
        <td><%= f.select :two_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :two_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>3</td>
        <td><%= f.select :three_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :three_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>4</td>
        <td><%= f.select :four_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :four_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr> 
      <tr>
        <td>5</td>
        <td><%= f.select :five_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :five_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr> 
      <tr>
        <td>6</td>
        <td><%= f.select :six_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :six_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr> 
      <tr>
        <td>7</td>
        <td><%= f.select :seven_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :seven_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr> 
      <tr>
        <td>8</td>
        <td><%= f.select :eight_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :eight_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr> 
      <tr>
        <td>9</td>
        <td><%= f.select :nine_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :nine_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr> 
      <tr>
        <td>先</td>
        <td>投</td>
        <td><%= f.collection_select :starting, @players_pitcher, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>中</td>
        <td>投</td>
        <td><%= f.collection_select :relief, @players_pitcher, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>抑</td>
        <td>投</td>
        <td><%= f.collection_select :closer, @players_pitcher, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
    </table>

    <%= f.hidden_field :user_id, :value => current_user.id %>
  
    <%= f.submit "確認", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/best_nines/create.html.erb
<h1>BestNines#create</h1>
<p>Find me in app/views/best_nines/create.html.erb</p>

app/views/best_nines/index.html.erb
<% provide(:title, "ホーム") %>

<div class="row">
  <div class="center jumbotron">
    <h1>カープベストナイン</h1>
  </div>

  <% @best_nines.each do |best_nine| %>
    <div class="col-sm-4 nine_table">
      <table border="1">
        <caption><%= link_to best_nine.title,  best_nine%></caption>
        <%= render "shared/mynine_table", best_nine: best_nine %>
      </table>
    </div>
  <% end %>

  <%= will_paginate %>
</div>

app/views/best_nines/new.html.erb
<h1>マイナイン作成</h1>

<div class="row">
  <%= form_with(model: @bestnine, url: {action: 'confirm'}, local: true) do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
    <table border="1">
      <caption><%= f.text_field :title, placeholder: "タイトル" %></caption>
      <tr>
        <th>打順</th><th>ポジション</th><th>名前</th>
      </tr>
      <tr>
        <td>1</td>
        <td><%= f.select :one_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :one_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>2</td>
        <td><%= f.select :two_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :two_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>3</td>
        <td><%= f.select :three_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :three_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>4</td>
        <td><%= f.select :four_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :four_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr> 
      <tr>
        <td>5</td>
        <td><%= f.select :five_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :five_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr> 
      <tr>
        <td>6</td>
        <td><%= f.select :six_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :six_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr> 
      <tr>
        <td>7</td>
        <td><%= f.select :seven_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :seven_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr> 
      <tr>
        <td>8</td>
        <td><%= f.select :eight_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :eight_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr> 
      <tr>
        <td>9</td>
        <td><%= f.select :nine_position, BestNine::POSITION, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :nine_name, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr> 
      <tr>
        <td>先</td>
        <td>投</td>
        <td><%= f.collection_select :starting, @players_pitcher, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>中</td>
        <td>投</td>
        <td><%= f.collection_select :relief, @players_pitcher, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>抑</td>
        <td>投</td>
        <td><%= f.collection_select :closer, @players_pitcher, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
    </table>

    <%= f.hidden_field :user_id, :value => current_user.id %>
  
    <%= f.submit "確認", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/best_nines/show.html.erb
<% provide(:title, "マイナイン詳細") %>

<div class="row">

  <div class="col-sm-4 nine_table">
    <table border="1">
      <caption><%= @best_nine.title %></caption>
      <%= render "shared/mynine_table", best_nine: @best_nine %>
    </table>
    <% if logged_in? && current_user?(current_user)%>
      <%= link_to "削除", @best_nine, method: :delete, data: {confirm: "本当によろしいですか？"}  %>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message.html_safe, class: "alert alert-#{message_type}") %>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MyNine", root_path, class: "navbar-brand" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "マイナイン作成", new_best_nine_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              設定 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザー情報", current_user %></li>
              <li class="divider"></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              新規登録・ログイン <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "新規登録", new_user_path %></li>
              <li class="divider"></li>          
              <li><%= link_to "ログイン", login_path %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Myナイン </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash" %>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>      
    </div>
  </body>
</html>

app/views/players/new.html.erb
<h1>ベストイレブン作成</h1>

<div class="row">
  <%= form_with(model: @player, local: true) do |f| %>
    <table border="1">
      <tr>
        <th>打順</th><th>ポジション</th><th>名前</th>
      </tr>
      <tr>
        <td>1</td>
        <td><%= f.select :position, {'捕': 2, '一': 3, '二': 4, '三': 5, '遊': 6, '左': 7, '中': 8, '右': 9}, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :player_id, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>2</td>
        <td><%= f.select :position, {'捕': 2, '一': 3, '二': 4, '三': 5, '遊': 6, '左': 7, '中': 8, '右': 9}, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :player_id, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>3</td>
        <td><%= f.select :position, {'捕': 2, '一': 3, '二': 4, '三': 5, '遊': 6, '左': 7, '中': 8, '右': 9}, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :player_id, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>4</td>
        <td><%= f.select :position, {'捕': 2, '一': 3, '二': 4, '三': 5, '遊': 6, '左': 7, '中': 8, '右': 9}, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :player_id, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>5</td>
        <td><%= f.select :position, {'捕': 2, '一': 3, '二': 4, '三': 5, '遊': 6, '左': 7, '中': 8, '右': 9}, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :player_id, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>6</td>
        <td><%= f.select :position, {'捕': 2, '一': 3, '二': 4, '三': 5, '遊': 6, '左': 7, '中': 8, '右': 9}, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :player_id, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>7</td>
        <td><%= f.select :position, {'捕': 2, '一': 3, '二': 4, '三': 5, '遊': 6, '左': 7, '中': 8, '右': 9}, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :player_id, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>8</td>
        <td><%= f.select :position, {'捕': 2, '一': 3, '二': 4, '三': 5, '遊': 6, '左': 7, '中': 8, '右': 9}, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :player_id, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>9</td>
        <td><%= f.select :position, {'捕': 2, '一': 3, '二': 4, '三': 5, '遊': 6, '左': 7, '中': 8, '右': 9}, {include_blank: true}, {class: 'form-control', required: true }  %></td>
        <td><%= f.collection_select :player_id, @players_fielder, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>先</td>
        <td>投</td>
        <td><%= f.collection_select :player_id, @players_pitcher, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>中</td>
        <td>投</td>
        <td><%= f.collection_select :player_id, @players_pitcher, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
      <tr>
        <td>抑</td>
        <td>投</td>
        <td><%= f.collection_select :player_id, @players_pitcher, :id, :player_name, { :include_blank => true }, class: 'form-control' %></td>
      </tr>
    </table>
  <% end %>

</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(model.errors.count, "error") %>.
    </div>
    <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_mynine_table.html.erb
<tr>
  <th>打順</th><th>ポジション</th><th>名前</th>
</tr>
<tr>
  <td>1</td>
  <td><%= BestNine::POSITION.key(best_nine.one_position) %></td>
  <td><%= @players.find(best_nine.one_name).player_name %></td>
</tr>
<tr>
  <td>2</td>
  <td><%= BestNine::POSITION.key(best_nine.two_position) %></td>
  <td><%= @players.find(best_nine.two_name).player_name %></td>
</tr>
<tr>
  <td>3</td>
  <td><%= BestNine::POSITION.key(best_nine.three_position) %></td>
  <td><%= @players.find(best_nine.three_name).player_name %></td>
</tr>
<tr>
  <td>4</td>
  <td><%= BestNine::POSITION.key(best_nine.four_position) %></td>
  <td><%= @players.find(best_nine.four_name).player_name %></td>
</tr> 
<tr>
  <td>5</td>
  <td><%= BestNine::POSITION.key(best_nine.five_position) %></td>
  <td><%= @players.find(best_nine.five_name).player_name %></td>
</tr> 
<tr>
  <td>6</td>
  <td><%= BestNine::POSITION.key(best_nine.six_position) %></td>
  <td><%= @players.find(best_nine.six_name).player_name %></td>
</tr> 
<tr>
  <td>7</td>
  <td><%= BestNine::POSITION.key(best_nine.seven_position) %></td>
  <td><%= @players.find(best_nine.seven_name).player_name %></td>
</tr> 
<tr>
  <td>8</td>
  <td><%= BestNine::POSITION.key(best_nine.eight_position) %></td>
  <td><%= @players.find(best_nine.eight_name).player_name %></td>
</tr> 
<tr>
  <td>9</td>
  <td><%= BestNine::POSITION.key(best_nine.nine_position) %></td>
  <td><%= @players.find(best_nine.nine_name).player_name %></td>
</tr> 
<tr>
  <td>先</td>
  <td>投</td>
  <td><%= @players.find(best_nine.starting).player_name %></td>
</tr>
<tr>
  <td>中</td>
  <td>投</td>
  <td><%= @players.find(best_nine.relief).player_name %></td>
</tr>
<tr>
  <td>抑</td>
  <td>投</td>
  <td><%= @players.find(best_nine.closer).player_name %></td>
</tr>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %> 
  <%= render 'shared/error_messages', model: f.object %>
  
  <div class="form_field">
    <%= f.text_field :name, class: 'form-control', placeholder: "ユーザーネーム" %>
  </div>

  <div class="form_field">
    <%= f.email_field :email, class: 'form-control', placeholder: "メールアドレス" %>
  </div>
  
  <div class="form_field">
    <%= f.password_field :password, class: 'form-control', placeholder: "パスワード(半角英数字8~32文字)" %>
  </div>
  
  <div class="form_field">
    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "パスワード(確認用)" %>
  </div>
  
  <div class="form_field">
    <%= f.submit yield(:submit), class: "form-control btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー編集")%>
<% provide(:submit, "変更する") %>

<h1>ユーザー編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "ユーザー作成") %>
<% provide(:submit, "登録する") %>

<h1>ユーザー作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2><%= @user.name %></h2>
    <p><%= @user.email %></p>

    <p><%= link_to "編集", edit_user_path(current_user), class: "form-control btn btn-primary" %></p>
  </div>
</div>